#!/usr/bin/env python
"""
sample_test

autogenerated sample test for test
"""
import unittest
import test

class SampleTest(unittest.TestCase):
    """placeholder for real tests"""
    def test_sample(self):
        self.failUnless(True)



if __name__ == '__main__':
    unittest.main()